name: release

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: subtitles-translate-helper
